image: node:20

stages:
  - test
  - build

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/
  key:
    files:
      - package-lock.json

test:
  stage: test
  script:
    - npm ci
    - npm run test -- --passWithNoTests
    - npm run lint
  allow_failure: true

build:
  stage: build
  script:
    - npm ci
    - node --version && npm --version
    - npm ls vite || echo "vite não está instalado"
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
  only:
    - main
    - develop
