export const opcoes = [
    {
      acao: "toggleBairros",
      estado: "bairros",
      icone: "🏘",
      label: "Bairros",
      value: "bairro",
      cor: "bg-gray-100 hover:bg-gray-200",
    },
    {
      acao: "toggleAssistencia",
      estado: "assistencia",
      icone: "🏥",
      label: "Assistência",
      value: "assistencia",
      cor: "bg-green-100 hover:bg-green-200",
    },
    {
      acao: "toggleHistoricos",
      estado: "historicos",
      icone: "🏛️",
      label: "Históricos",
      value: "historico",
      cor: "bg-yellow-100 hover:bg-yellow-200",
    },
    {
      acao: "toggleCulturais",
      estado: "culturais",
      icone: "🎭",
      label: "Lazer",
      value: "lazer",
      cor: "bg-blue-100 hover:bg-blue-200",
    },
    {
      acao: "toggleComunidades",
      estado: "comunidades",
      icone: "👥",
      label: "Comunidades",
      value: "comunidades",
      cor: "bg-red-100 hover:bg-red-200",
    },
    {
      acao: "toggleEducação",
      estado: "educação",
      icone: "📚",
      label: "Educação",
      value: "educação",
      cor: "bg-purple-100 hover:bg-purple-200",
    },
    {
      acao: "toggleReligiao",
      estado: "religiao",
      icone: "⛪",
      label: "Religião",
      value: "religiao",
      cor: "bg-gray-100 hover:bg-gray-200",
    },
  ];
  
  export const crosshairColorMap = {
    bairro: "#9CA3AF",
    assistencia: "#10B981",
    historico: "#FBBF24",
    lazer: "#3B82F6",
    comunidades: "#EF4444",
    educação: "#8B5CF6",
    religiao: "#4B5563",
  };